<a href="https://colab.research.google.com/github/Sakibcheez/SakibPy/blob/main/numpy_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# 1. Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("1. Basic arrays:")
print("1D array:", arr1)
print("2D array:\n", arr2)

1. Basic arrays:
1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


In [3]:
# 2. Array properties
print("\n2. Array properties:")
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data type:", arr2.dtype)


2. Array properties:
Shape: (2, 3)
Size: 6
Data type: int64


In [5]:
print("\n3. Array Properties:")
print("Shape:", arr1.shape)
print("Size:", arr1.size)
print("Data type:", arr1.dtype)


3. Array Properties:
Shape: (5,)
Size: 5
Data type: int64


In [6]:
# 3. Creating special arrays
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
identity = np.eye(3)
print("\n3. Special arrays:")
print("Zeros array:\n", zeros)
print("Ones array:\n", ones)
print("Identity matrix:\n", identity)

# 4. Array indexing and slicing
arr = np.array([10, 20, 30, 40, 50])
print("\n4. Indexing and slicing:")
print("Element at index 2:", arr[2])
print("Slice [1:4]:", arr[1:4])
print("Last element:", arr[-1])


3. Special arrays:
Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Indexing and slicing:
Element at index 2: 30
Slice [1:4]: [20 30 40]
Last element: 50


In [8]:
# 5. Mathematical operations
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print("\n5. Mathematical operations:")
print("Addition:", a + b)
print("Multiplication:", a * b)
print("Square root:", np.sqrt(a))

# 6. Statistical functions
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("\n6. Statistical functions:")
print("Mean:", np.mean(data))
print("Standard deviation:", np.std(data))
print("Max:", np.max(data))
print("Min:", np.min(data))


5. Mathematical operations:
Addition: [ 6  8 10 12]
Multiplication: [ 5 12 21 32]
Square root: [1.         1.41421356 1.73205081 2.        ]

6. Statistical functions:
Mean: 5.5
Standard deviation: 2.8722813232690143
Max: 10
Min: 1


In [9]:
# 7. Reshaping arrays
original = np.array([1, 2, 3, 4, 5, 6])
reshaped = original.reshape(2, 3)
print("\n7. Reshaping:")
print("Original:", original)
print("Reshaped (2x3):\n", reshaped)

# 8. Boolean indexing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = arr > 5
print("\n8. Boolean indexing:")
print("Original array:", arr)
print("Elements > 5:", arr[mask])


7. Reshaping:
Original: [1 2 3 4 5 6]
Reshaped (2x3):
 [[1 2 3]
 [4 5 6]]

8. Boolean indexing:
Original array: [ 1  2  3  4  5  6  7  8  9 10]
Elements > 5: [ 6  7  8  9 10]


In [10]:
# 9. Random number generation
print("\n9. Random numbers:")
print("Random integers:", np.random.randint(1, 10, 5))
print("Random floats:", np.random.random(5))
print("Normal distribution:", np.random.normal(0, 1, 5))

# 10. Linear algebra
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print("\n10. Linear algebra:")
print("Matrix multiplication:\n", np.dot(matrix1, matrix2))
print("Determinant:", np.linalg.det(matrix1))


9. Random numbers:
Random integers: [9 4 9 2 2]
Random floats: [0.8156105  0.71862462 0.39294221 0.04910837 0.9924537 ]
Normal distribution: [-0.34982058  1.01587057  0.10449034 -0.6032977   0.519774  ]

10. Linear algebra:
Matrix multiplication:
 [[19 22]
 [43 50]]
Determinant: -2.0000000000000004


In [11]:
# Create a NumPy array with many decimal places
arr = np.array([1.123456789, 2.987654321, 3.1415926535])
print("Original array:")
print(arr)

# Set precision to 3 decimal places
np.set_printoptions(precision=3)
print("\nArray with precision set to 3:")
print(arr)

# Reset print options to default
np.set_printoptions(precision=8) # Default precision is usually 8

Original array:
[1.12345679 2.98765432 3.14159265]

Array with precision set to 3:
[1.123 2.988 3.142]
